// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhBeHdYqqyWqRDaJXdM0bAueRMS31uTXE',
    appId: '1:38590816711:web:3fd33a2ff8d642435eb9e2',
    messagingSenderId: '38590816711',
    projectId: 'food-delivery-demo-92033',
    authDomain: 'food-delivery-demo-92033.firebaseapp.com',
    storageBucket: 'food-delivery-demo-92033.appspot.com',
    measurementId: 'G-1SDC8CSJ7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_04B9C1gmO2jy-PfjiTP5-0KO9ffPeqk',
    appId: '1:38590816711:android:ded9e8fd875ebb185eb9e2',
    messagingSenderId: '38590816711',
    projectId: 'food-delivery-demo-92033',
    storageBucket: 'food-delivery-demo-92033.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoBQVa0eb5pVIrXZmOgnD0abGAIBkft0E',
    appId: '1:38590816711:ios:bbf352741101289f5eb9e2',
    messagingSenderId: '38590816711',
    projectId: 'food-delivery-demo-92033',
    storageBucket: 'food-delivery-demo-92033.appspot.com',
    iosBundleId: 'com.example.foodAppTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoBQVa0eb5pVIrXZmOgnD0abGAIBkft0E',
    appId: '1:38590816711:ios:fb219a773bfcde2b5eb9e2',
    messagingSenderId: '38590816711',
    projectId: 'food-delivery-demo-92033',
    storageBucket: 'food-delivery-demo-92033.appspot.com',
    iosBundleId: 'com.example.foodAppTest.RunnerTests',
  );
}
